apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"downscaler","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"kube-downscaler","app.kubernetes.io/version":"22.9.0","helm.sh/chart":"kube-downscaler-0.7.0"},"name":"downscaler-kube-downscaler","namespace":"vote"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"downscaler","app.kubernetes.io/name":"kube-downscaler"}},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"downscaler","app.kubernetes.io/name":"kube-downscaler"}},"spec":{"containers":[{"args":["--interval=60","--enable-events"],"image":"hjacobs/kube-downscaler:22.9.0","imagePullPolicy":"IfNotPresent","name":"downscaler-kube-downscaler","resources":{"limits":{"cpu":"50m","memory":"200Mi"},"requests":{"cpu":"50m","memory":"200Mi"}},"securityContext":{}}],"serviceAccountName":"downscaler-kube-downscaler"}}}}
  creationTimestamp: '2023-01-26T09:14:16Z'
  generation: 5
  labels:
    app.kubernetes.io/instance: downscaler
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-downscaler
    app.kubernetes.io/version: 22.9.0
    helm.sh/chart: kube-downscaler-0.7.0
  name: downscaler-kube-downscaler
  namespace: vote
  resourceVersion: '243291'
  uid: 6289b2f7-11e3-4e95-ba80-c4013ebbf3fb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: downscaler
      app.kubernetes.io/name: kube-downscaler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: downscaler
        app.kubernetes.io/name: kube-downscaler
    spec:
      containers:
        - args:
              - --interval={{ .Values.interval }}
              {{- if .Values.namespace }}
              {{- if .Values.namespace.active_in }}
              - --namespace={{ .Values.namespace.active_in }}
              {{- end }}
              {{- if .Values.namespace.inactive_in }}
              - --exclude-namespaces={{ .Values.namespace.inactive_in | join "," }}
              {{- end }}
          image: 'hjacobs/kube-downscaler:22.9.0'
          imagePullPolicy: IfNotPresent
          name: downscaler-kube-downscaler
          resources:
            limits:
              cpu: 50m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 200Mi
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: downscaler-kube-downscaler
      serviceAccountName: downscaler-kube-downscaler
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2023-01-26T09:14:16Z'
      lastUpdateTime: '2023-02-02T01:07:41Z'
      message: >-
        ReplicaSet "downscaler-kube-downscaler-5999894cf7" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: '2023-02-02T10:06:21Z'
      lastUpdateTime: '2023-02-02T10:06:21Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
