apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    name: postgres-deploy
spec:
  replicas: {{ .Values.postgres.replicaCount}}
  selector:
    matchLabels:
      {{- include "mychart.labels" . | nindent 6 }}
      name: postgres-pod
  template:
    metadata:
      name: postgres-pod
      labels:
        {{- include "mychart.labels" . | nindent 8 }}
        name: postgres-pod
    spec:
      containers:
        - name: postgres  
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"    
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust