apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: demo-voting-app
    name: voting-service 
spec:
  type: NodePort
  ports:
     - port: 80
       targetPort: 80
       nodePort: 30006
  selector:
   app: demo-voting-app
   name: voting-app-pod
     